#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

case $(uname) in
  *CYGWIN*|*MINGW*|*MSYS*) # inspiration : https://github.com/desktop/desktop/issues/10326#issuecomment-751263702
    npx.cmd lint-staged # bug on Windows/Github Desktop: add `.cmd` extension fixes it
    poetry run nbdev_clean --fname .
  ;;
  *)
    npx lint-staged
    poetry run nbdev_clean --fname .
  ;;
esac
